"""Add missing relationships

Revision ID: 863cb0fe2f62
Revises: 3205ae7c8331
Create Date: 2025-05-12 02:37:16.778841

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '863cb0fe2f62'
down_revision = '3205ae7c8331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'buildingevent', 'village', ['village_id'], ['id'])
    op.create_foreign_key(None, 'unittrainingevent', 'village', ['village_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unittrainingevent', type_='foreignkey')
    op.drop_constraint(None, 'buildingevent', type_='foreignkey')
    # ### end Alembic commands ###
